# Generated by Django 3.2.16 on 2025-02-10 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Maestro asignado*'),
        ),
        migrations.AddField(
            model_name='materias',
            name='nombre_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_cursos.cursos', verbose_name='Curso*'),
        ),
    ]
