# Generated by Django 3.2.16 on 2025-02-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'default_permissions': (), 'managed': False, 'permissions': (('registrar_rol', 'Puede Registrar Rol'), ('consultar_roles', 'Puede Consultar Roles'), ('actualizar_rol', 'Puede Actualizar Rol'), ('eliminar_rol', 'Puede eliminar Rol'))},
        ),
    ]
