# Generated by Django 3.2.16 on 2025-02-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_alter_roles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'default_permissions': (), 'managed': False, 'permissions': (('registrar_rol', 'Puede Registrar Rol'), ('listar_roles', 'Puede Consultar Roles'), ('actualizar_rol', 'Puede Actualizar Rol'), ('eliminar_rol', 'Puede eliminar Rol'))},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'default_permissions': (), 'ordering': ['-first_name'], 'permissions': (('registrar_usuario', 'Puede Registrar Usuario'), ('listar_usuarios', 'Puede Consultar Usuarios'), ('actualizar_usuario', 'Puede Actualizar Usuario'), ('eliminar_usuario', 'Puede Eliminar Usuario'), ('detalle_usuario', 'Puede Ver Detalle Usuario'))},
        ),
    ]
