# Generated by Django 3.2.16 on 2025-02-10 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhecha_inscripcion', models.DateField(verbose_name='Fecha incripcion*')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_cursos.cursos', verbose_name='Cursos por elegir*')),
            ],
            options={
                'permissions': (('registrar_inscripcion', 'Puede Crear inscripcion'), ('listar_inscripciones', 'Puede Consultar inscripciones'), ('actualizar_inscripcion', 'Puede Actualizar inscripcion'), ('eliminar_inscripcion', 'Puede Eliminar inscripcion')),
                'default_permissions': (),
            },
        ),
    ]
